package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * AggMarkerResultBO generated by hbm2java
 */
public class AggMarkerResultBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private AggregateBO aggregate;
	private Double wsmxdxct;
	private Double wsmnormct;
	private Double medianxdxct;
	private Double platestddev;
	private Double wsmBaselineFam;
	private Double wsmSaturationFam;
	private String errortype;
	private Set<MarkerBO> markers = new HashSet<MarkerBO>(0);

	public AggMarkerResultBO() {
	}

	public AggMarkerResultBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public AggMarkerResultBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection, AggregateBO aggregate,
			Double wsmxdxct, Double wsmnormct,
			Double medianxdxct, Double platestddev,
			Double wsmBaselineFam, Double wsmSaturationFam,
			String errortype,
			Set<MarkerBO> markers) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.aggregate = aggregate;
		this.wsmxdxct = wsmxdxct;
		this.wsmnormct = wsmnormct;
		this.medianxdxct = medianxdxct;
		this.platestddev = platestddev;
		this.wsmBaselineFam = wsmBaselineFam;
		this.wsmSaturationFam = wsmSaturationFam;
		this.errortype = errortype;
		this.markers = markers;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	public AggregateBO getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(AggregateBO aggregate) {
		this.aggregate = aggregate;
	}

	public Double getWsmxdxct() {
		return this.wsmxdxct;
	}

	public void setWsmxdxct(Double wsmxdxct) {
		this.wsmxdxct = wsmxdxct;
	}

	public Double getWsmnormct() {
		return this.wsmnormct;
	}

	public void setWsmnormct(Double wsmnormct) {
		this.wsmnormct = wsmnormct;
	}

	public Double getMedianxdxct() {
		return this.medianxdxct;
	}

	public void setMedianxdxct(Double medianxdxct) {
		this.medianxdxct = medianxdxct;
	}

	public Double getPlatestddev() {
		return this.platestddev;
	}

	public void setPlatestddev(Double platestddev) {
		this.platestddev = platestddev;
	}

	/**
	 * @return the wsmBaselineFam
	 */
	public Double getWsmBaselineFam() {
		return wsmBaselineFam;
	}

	/**
	 * @param wsmBaselineFam the wsmBaselineFam to set
	 */
	public void setWsmBaselineFam(Double wsmBaselineFam) {
		this.wsmBaselineFam = wsmBaselineFam;
	}

	/**
	 * @return the wsmSaturationFam
	 */
	public Double getWsmSaturationFam() {
		return wsmSaturationFam;
	}

	/**
	 * @param wsmSaturationFam the wsmSaturationFam to set
	 */
	public void setWsmSaturationFam(Double wsmSaturationFam) {
		this.wsmSaturationFam = wsmSaturationFam;
	}

	public String getErrortype() {
		return this.errortype;
	}

	public void setErrortype(String errortype) {
		this.errortype = errortype;
	}

	public Set<MarkerBO> getMarkers() {
		return this.markers;
	}

	public void setMarkers(Set<MarkerBO> markers) {
		this.markers = markers;
	}

}
