package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * ConfigBO generated by hbm2java
 */
public class AggregateBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private PlateSectionBO plateSection;
	
	public AggregateBO() {
	}

	public AggregateBO(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public PlateSectionBO getPlateSection() {
		return this.plateSection;
	}

	public void setPlateSection(PlateSectionBO plateSection) {
		this.plateSection = plateSection;
	}
}
