package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * AggSectionResultBO generated by hbm2java
 */
public class AggSectionResultBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private Double algoscore;
	private Double mappedscore;
	private Double mappedlowscore;
	private Double mappedhighscore;
	private String qcstatus;
	private String qcfailreason;
	private String qcdoneby;
	private Date qcdate;

	public AggSectionResultBO() {
	}

	public AggSectionResultBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public AggSectionResultBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection, Double algoscore, Double mappedscore,
			Double mappedlowscore, Double mappedhighscore, String qcstatus,
			String qcfailreason, String qcdoneby, Date qcdate) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.algoscore = algoscore;
		this.mappedscore = mappedscore;
		this.mappedlowscore = mappedlowscore;
		this.mappedhighscore = mappedhighscore;
		this.qcstatus = qcstatus;
		this.qcfailreason = qcfailreason;
		this.qcdoneby = qcdoneby;
		this.qcdate = qcdate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	public Double getAlgoscore() {
		return this.algoscore;
	}

	public void setAlgoscore(Double algoscore) {
		this.algoscore = algoscore;
	}

	public Double getMappedscore() {
		return this.mappedscore;
	}

	public void setMappedscore(Double mappedscore) {
		this.mappedscore = mappedscore;
	}

	public Double getMappedlowscore() {
		return this.mappedlowscore;
	}

	public void setMappedlowscore(Double mappedlowscore) {
		this.mappedlowscore = mappedlowscore;
	}

	public Double getMappedhighscore() {
		return this.mappedhighscore;
	}

	public void setMappedhighscore(Double mappedhighscore) {
		this.mappedhighscore = mappedhighscore;
	}

	public String getQcstatus() {
		return this.qcstatus;
	}

	public void setQcstatus(String qcstatus) {
		this.qcstatus = qcstatus;
	}

	public String getQcfailreason() {
		return this.qcfailreason;
	}

	public void setQcfailreason(String qcfailreason) {
		this.qcfailreason = qcfailreason;
	}

	public String getQcdoneby() {
		return this.qcdoneby;
	}

	public void setQcdoneby(String qcdoneby) {
		this.qcdoneby = qcdoneby;
	}

	public Date getQcdate() {
		return this.qcdate;
	}

	public void setQcdate(Date qcdate) {
		this.qcdate = qcdate;
	}

}
