package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * AggMarkerResultBO generated by hbm2java
 */
public class AssayOutlierResultBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private MarkerBO marker;
	private Boolean pass;

	public AssayOutlierResultBO() {
	}

	public AssayOutlierResultBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public AssayOutlierResultBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection, MarkerBO aggregate,
			Boolean pass) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.marker = aggregate;
		this.pass = pass;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	public MarkerBO getMarker() {
		return this.marker;
	}

	public void setMarker(MarkerBO aggregate) {
		this.marker = aggregate;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

}
