package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * ConfigBO generated by hbm2java
 */
public class ConfigBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private TestcodeBO testcode;
	private String name;
	private String value;
	private String configtype;

	public ConfigBO() {
	}

	public ConfigBO(long id, String name, String configtype) {
		this.id = id;
		this.name = name;
		this.configtype = configtype;
	}

	public ConfigBO(long id, TestcodeBO testcode, String name, String value,
			String configtype) {
		this.id = id;
		this.testcode = testcode;
		this.name = name;
		this.value = value;
		this.configtype = configtype;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TestcodeBO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeBO testcode) {
		this.testcode = testcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getConfigtype() {
		return this.configtype;
	}

	public void setConfigtype(String configtype) {
		this.configtype = configtype;
	}

}
