package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MarkerBO generated by hbm2java
 */
public class MarkerBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private MarkerTypeBO markertype;
	private String name;
	private Set<AggMarkerResultBO> aggmarkerresults = new HashSet<AggMarkerResultBO>(0);
	private Set<PlateDesignDetailBO> platedesigndetails = new HashSet<PlateDesignDetailBO>(0);
	private Set<ProcessControlDetailBO> processcontroldetails = new HashSet<ProcessControlDetailBO>(0);

	public MarkerBO() {
	}

	public MarkerBO(long id, MarkerTypeBO markertype, String name) {
		this.id = id;
		this.markertype = markertype;
		this.name = name;
	}

	public MarkerBO(long id, MarkerTypeBO markertype, String name,
			Set<AggMarkerResultBO> aggmarkerresults, Set<PlateDesignDetailBO> platedesigndetails) {
		this.id = id;
		this.markertype = markertype;
		this.name = name;
		this.aggmarkerresults = aggmarkerresults;
		this.platedesigndetails = platedesigndetails;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public MarkerTypeBO getMarkertype() {
		return this.markertype;
	}

	public void setMarkertype(MarkerTypeBO markertype) {
		this.markertype = markertype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<AggMarkerResultBO> getAggmarkerresults() {
		return this.aggmarkerresults;
	}

	public void setAggmarkerresults(Set<AggMarkerResultBO> aggmarkerresults) {
		this.aggmarkerresults = aggmarkerresults;
	}

	public Set<PlateDesignDetailBO> getPlatedesigndetails() {
		return this.platedesigndetails;
	}

	public void setPlatedesigndetails(Set<PlateDesignDetailBO> platedesigndetails) {
		this.platedesigndetails = platedesigndetails;
	}

	public Set<ProcessControlDetailBO> getProcesscontroldetails() {
		return this.processcontroldetails;
	}

	public void setProcesscontroldetails(Set<ProcessControlDetailBO> processcontroldetails) {
		this.processcontroldetails = processcontroldetails;
	}

}
