package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MarkerTypeBO generated by hbm2java
 */
public class MarkerTypeBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private Set<MarkerBO> markers = new HashSet<MarkerBO>(0);

	public MarkerTypeBO() {
	}

	public MarkerTypeBO(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public MarkerTypeBO(long id, String name, Set<MarkerBO> markers) {
		this.id = id;
		this.name = name;
		this.markers = markers;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<MarkerBO> getMarkers() {
		return this.markers;
	}

	public void setMarkers(Set<MarkerBO> markers) {
		this.markers = markers;
	}

}
