package com.xdx.sax.bo;

/**
 * TestcodeBO generated by hbm2java
 */
public class OldPlateMapBO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String name;
	private long wellName;
	private long section;
	private String markerName;
	
	public OldPlateMapBO() {
	}

	public OldPlateMapBO(long id, String name, long wellName,
			long section, String markerName) {
		this.id = id;
		this.name = name;
		this.wellName = wellName;
		this.section = section;
		this.markerName = markerName;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getWellName() {
		return this.wellName;
	}

	public void setWellName(long wellName) {
		this.wellName = wellName;
	}

	public long getSection() {
		return this.section;
	}

	public void setSection(long section) {
		this.section = section;
	}

	public String getMarkerName() {
		return this.markerName;
	}

	public void setMarkerName(String markerName) {
		this.markerName = markerName;
	}

}
