package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * AggMarkerResultBO generated by hbm2java
 */
public class PlateSectionDetailBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private ProcessControlBO processcontrol;
	private boolean isEmpty;

	public PlateSectionDetailBO() {
	}

	public PlateSectionDetailBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection, boolean isEmpty) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.isEmpty = isEmpty;
	}

	public PlateSectionDetailBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection, ProcessControlBO processcontrol,
			boolean isEmpty) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.processcontrol = processcontrol;
		this.isEmpty = isEmpty;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	public ProcessControlBO getProcesscontrol() {
		return this.processcontrol;
	}

	public void setProcesscontrol(ProcessControlBO pd) {
		this.processcontrol = pd;
	}

	public boolean getIsEmpty() {
		return this.isEmpty;
	}

	public void setIsEmpty(boolean isEmpty) {
		this.isEmpty = isEmpty;
	}

}
