package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlateBO generated by hbm2java
 */
public class PlateBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetBO plateset;
	private String platebarcode;
	private long numberinset;
	private Date processedTimestamp;
	private Date registeredTimestamp;
	private Long processorError;
	private String qcResult;
	private String qcFailReason;
	private String qcComment;
	private String qcDoneBy;
	private Date qcDate;
	private String instrumentSerialNumber;
	private Date instrumentRunTime;
	private Set<RawWellDataBO> rawwelldatas = new HashSet<RawWellDataBO>(0);

	public PlateBO() {
	}

	public PlateBO(int id, PlateSetBO plateset, String platebarcode,
			int numberinset) {
		this.id = id;
		this.plateset = plateset;
		this.platebarcode = platebarcode;
		this.numberinset = numberinset;
	}

	public PlateBO(int id, PlateSetBO plateset, String platebarcode,
			int numberinset, Set<RawWellDataBO> rawwelldatas, 
			Date processedTimestamp, Date registeredTimestamp,
			Long processorError) {
		this.id = id;
		this.plateset = plateset;
		this.platebarcode = platebarcode;
		this.numberinset = numberinset;
		this.processedTimestamp = processedTimestamp;
		this.registeredTimestamp = registeredTimestamp;
		this.rawwelldatas = rawwelldatas;
		this.processorError = processorError;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public String getPlatebarcode() {
		return this.platebarcode;
	}

	public void setPlatebarcode(String platebarcode) {
		this.platebarcode = platebarcode;
	}

	public long getNumberinset() {
		return this.numberinset;
	}

	public void setNumberinset(long plateNum) {
		this.numberinset = plateNum;
	}

	public Date getProcessedTimestamp() {
		return processedTimestamp;
	}

	public void setProcessedTimestamp(Date processedTimestamp) {
		this.processedTimestamp = processedTimestamp;
	}

	/**
	 * @return the registeredTimestamp
	 */
	public Date getRegisteredTimestamp() {
		return registeredTimestamp;
	}

	/**
	 * @param registeredTimestamp the registeredTimestamp to set
	 */
	public void setRegisteredTimestamp(Date registeredTimestamp) {
		this.registeredTimestamp = registeredTimestamp;
	}

	/**
	 * @return the qcResult
	 */
	public String getQcResult() {
		return qcResult;
	}

	/**
	 * @param qcResult the qcResult to set
	 */
	public void setQcResult(String qcResult) {
		this.qcResult = qcResult;
	}

	/**
	 * @return the qcFailReason
	 */
	public String getQcFailReason() {
		return qcFailReason;
	}

	/**
	 * @param qcFailReason the qcFailReason to set
	 */
	public void setQcFailReason(String qcFailReason) {
		this.qcFailReason = qcFailReason;
	}

	/**
	 * @return the qcComment
	 */
	public String getQcComment() {
		return qcComment;
	}

	/**
	 * @param qcComment the qcComment to set
	 */
	public void setQcComment(String qcComment) {
		this.qcComment = qcComment;
	}

	/**
	 * @return the qcDoneBy
	 */
	public String getQcDoneBy() {
		return qcDoneBy;
	}

	/**
	 * @param qcDoneBy the qcDoneBy to set
	 */
	public void setQcDoneBy(String qcDoneBy) {
		this.qcDoneBy = qcDoneBy;
	}

	/**
	 * @return the qcDate
	 */
	public Date getQcDate() {
		return qcDate;
	}

	/**
	 * @param qcDate the qcDate to set
	 */
	public void setQcDate(Date qcDate) {
		this.qcDate = qcDate;
	}

	public Set<RawWellDataBO> getRawwelldatas() {
		return this.rawwelldatas;
	}

	public void setRawwelldatas(Set<RawWellDataBO> rawwelldatas) {
		this.rawwelldatas = rawwelldatas;
	}

	public Long getProcessorError() {
		return this.processorError;
	}

	public void setProcessorError(Long processorError) {
		this.processorError = processorError;
	}

	/**
	 * @return the instrumentSerialNumber
	 */
	public String getInstrumentSerialNumber() {
		return instrumentSerialNumber;
	}

	/**
	 * @param instrumentSerialNumber the instrumentSerialNumber to set
	 */
	public void setInstrumentSerialNumber(String instrumentSerialNumber) {
		this.instrumentSerialNumber = instrumentSerialNumber;
	}

	/**
	 * @return the instrumentRunTime
	 */
	public Date getInstrumentRunTime() {
		return instrumentRunTime;
	}

	/**
	 * @param instrumentRunTime the instrumentRunTime to set
	 */
	public void setInstrumentRunTime(Date instrumentRunTime) {
		this.instrumentRunTime = instrumentRunTime;
	}

	public boolean isProcessorError() {
		return (getProcessorError() == null || getProcessorError() != 0);
	}

}
