package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlateSetBO generated by hbm2java
 */
public class PlateSetBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String externalId;
	private PlateDesignBO platedesign;
	private TestcodeBO testcode;
	private Date processedTimestamp;
	private Date registeredTimestamp;
	private Set<PlateSectionDetailBO> platesectiondetails = new HashSet<PlateSectionDetailBO>(0);
	private Set<AggSectionResultBO> aggsectionresults = new HashSet<AggSectionResultBO>(0);
	private Set<PlateProcessControlBO> plateprocesscontrols = new HashSet<PlateProcessControlBO>(0);
	private Set<QcResultFinalBO> qcresultfinals = new HashSet<QcResultFinalBO>(0);
	private Set<PlateBO> plates = new HashSet<PlateBO>(0);
	private Set<AggMarkerResultBO> aggmarkerresults = new HashSet<AggMarkerResultBO>(0);
	private Set<QcCriteriaStepResultBO> qccriteriastepresults = new HashSet<QcCriteriaStepResultBO>(0);

	public PlateSetBO() {
	}

	public PlateSetBO(int id, String externalId, 
			PlateDesignBO platedesign, TestcodeBO testcode) {
		this.id = id;
		this.externalId = externalId;
		this.platedesign = platedesign;
		this.testcode = testcode;
	}

	public PlateSetBO(int id, PlateDesignBO platedesign, TestcodeBO testcode,
			Date processedTimestamp, Date registeredTimestamp, Set<PlateSectionDetailBO> platesectiondetails,
			Set<AggSectionResultBO> aggsectionresults, Set<QcResultFinalBO> qcresultfinals, Set<PlateBO> plates,
			Set<AggMarkerResultBO> aggmarkerresults, Set<QcCriteriaStepResultBO> qccriteriastepresults) {
		this.id = id;
		this.platedesign = platedesign;
		this.testcode = testcode;
		this.processedTimestamp = processedTimestamp;
		this.registeredTimestamp = registeredTimestamp;
		this.platesectiondetails = platesectiondetails;
		this.aggsectionresults = aggsectionresults;
		this.qcresultfinals = qcresultfinals;
		this.plates = plates;
		this.aggmarkerresults = aggmarkerresults;
		this.qccriteriastepresults = qccriteriastepresults;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long plateSetId) {
		this.id = plateSetId;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public PlateDesignBO getPlatedesign() {
		return this.platedesign;
	}

	public void setPlatedesign(PlateDesignBO platedesign) {
		this.platedesign = platedesign;
	}

	public TestcodeBO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeBO testcode) {
		this.testcode = testcode;
	}

	/**
	 * @return the processedTimestamp
	 */
	public Date getProcessedTimestamp() {
		return processedTimestamp;
	}

	/**
	 * @param processedTimestamp the processedTimestamp to set
	 */
	public void setProcessedTimestamp(Date processedTimestamp) {
		this.processedTimestamp = processedTimestamp;
	}

	/**
	 * @return the registeredTimestamp
	 */
	public Date getRegisteredTimestamp() {
		return registeredTimestamp;
	}

	/**
	 * @param registeredTimestamp the registeredTimestamp to set
	 */
	public void setRegisteredTimestamp(Date registeredTimestamp) {
		this.registeredTimestamp = registeredTimestamp;
	}

	/**
	 * @return the platesectiondetails
	 */
	public Set<PlateSectionDetailBO> getPlatesectiondetails() {
		return platesectiondetails;
	}

	/**
	 * @param platesectiondetails the platesectiondetails to set
	 */
	public void setPlatesectiondetails(Set<PlateSectionDetailBO> platesectiondetails) {
		this.platesectiondetails = platesectiondetails;
	}

	public Set<AggSectionResultBO> getAggsectionresults() {
		return this.aggsectionresults;
	}

	public void setAggsectionresults(Set<AggSectionResultBO> aggsectionresults) {
		this.aggsectionresults = aggsectionresults;
	}

	public Set<PlateProcessControlBO> getPlateprocesscontrols() {
		return this.plateprocesscontrols;
	}

	public void setPlateprocesscontrols(Set<PlateProcessControlBO> plateprocesscontrols) {
		this.plateprocesscontrols = plateprocesscontrols;
	}

	public Set<QcResultFinalBO> getQcresultfinals() {
		return this.qcresultfinals;
	}

	public void setQcresultfinals(Set<QcResultFinalBO> qcresultfinals) {
		this.qcresultfinals = qcresultfinals;
	}

	public Set<PlateBO> getPlates() {
		return this.plates;
	}

	public void setPlates(Set<PlateBO> plates) {
		this.plates = plates;
	}

	public Set<AggMarkerResultBO> getAggmarkerresults() {
		return this.aggmarkerresults;
	}

	public void setAggmarkerresults(Set<AggMarkerResultBO> aggmarkerresults) {
		this.aggmarkerresults = aggmarkerresults;
	}

	public Set<QcCriteriaStepResultBO> getQccriteriastepresults() {
		return this.qccriteriastepresults;
	}

	public void setQccriteriastepresults(Set<QcCriteriaStepResultBO> qccriteriastepresults) {
		this.qccriteriastepresults = qccriteriastepresults;
	}

}
