package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * PlateProcessControl generated by hbm2java
 */
public class PlateProcessControlBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlBO processcontrol;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private Boolean isOk;
	private String failureReason;

	public PlateProcessControlBO() {
	}

	public PlateProcessControlBO(long id, ProcessControlBO processcontrol,
			PlateSetBO plateset, PlateSectionBO platesection) {
		this.id = id;
		this.processcontrol = processcontrol;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlBO getProcesscontrol() {
		return this.processcontrol;
	}

	public void setProcesscontrol(ProcessControlBO processcontrol) {
		this.processcontrol = processcontrol;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	/**
	 * @return the isOk
	 */
	public Boolean getIsOk() {
		return isOk;
	}

	/**
	 * @param isOk the isOk to set
	 */
	public void setIsOk(Boolean isOk) {
		this.isOk = isOk;
	}

	/**
	 * @return the failureReason
	 */
	public String getFailureReason() {
		return failureReason;
	}

	/**
	 * @param failureReason the failureReason to set
	 */
	public void setFailureReason(String failureReason) {
		this.failureReason = failureReason;
	}

}
