package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PlateDesignDetailBO generated by hbm2java
 */
public class PlateDesignDetailBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateDesignBO plateDesign;
	private AggregateBO aggregate;
	private WellTypeBO wellType;
	private PlateSectionBO plateSection;
	private long numberInSet;
	private long plateRow;
	private long plateColumn;
	private Set<MarkerBO> markers = new HashSet<MarkerBO>(0);

	public PlateDesignDetailBO() {
	}

	public PlateDesignDetailBO(long id, PlateDesignBO platedesign,
			PlateSectionBO platesection, long numberinset,
			long platerow, long platecolumn) {
		this.id = id;
		this.plateDesign = platedesign;
		this.plateSection = platesection;
		this.numberInSet = numberinset;
		this.plateRow = platerow;
		this.plateColumn = platecolumn;
	}

	public PlateDesignDetailBO(long id, PlateDesignBO platedesign, WellTypeBO wellType,
			AggregateBO aggregate, PlateSectionBO platesection, long numberinset,
			long platerow, long platecolumn, Set<MarkerBO> markers) {
		this.id = id;
		this.plateDesign = platedesign;
		this.wellType = wellType;
		this.aggregate = aggregate;
		this.plateSection = platesection;
		this.numberInSet = numberinset;
		this.plateRow = platerow;
		this.plateColumn = platecolumn;
		this.markers = markers;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateDesignBO getPlatedesign() {
		return this.plateDesign;
	}

	public void setPlatedesign(PlateDesignBO platedesign) {
		this.plateDesign = platedesign;
	}

	public AggregateBO getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(AggregateBO aggregate) {
		this.aggregate = aggregate;
	}

	public WellTypeBO getWellType() {
		return this.wellType;
	}

	public void setWellType(WellTypeBO wellType) {
		this.wellType = wellType;
	}

	public PlateSectionBO getPlatesection() {
		return this.plateSection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.plateSection = platesection;
	}

	public long getNumberinset() {
		return this.numberInSet;
	}

	public void setNumberinset(long numberinset) {
		this.numberInSet = numberinset;
	}

	public long getPlaterow() {
		return this.plateRow;
	}

	public void setPlaterow(long platerow) {
		this.plateRow = platerow;
	}

	public long getPlatecolumn() {
		return this.plateColumn;
	}

	public void setPlatecolumn(long platecolumn) {
		this.plateColumn = platecolumn;
	}

	public Set<MarkerBO> getMarkers() {
		return this.markers;
	}

	public void setMarkers(Set<MarkerBO> markers) {
		this.markers = markers;
	}

}
