package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PlateSectionBO generated by hbm2java
 */
public class PlateSectionBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateDesignBO platedesign;
	private String name;
	private Set<AggregateBO> aggregates = new HashSet<AggregateBO>(0);
	private Set<QcResultFinalBO> qcresultfinals = new HashSet<QcResultFinalBO>(0);
	private Set<PlateProcessControlBO> plateprocesscontrols = new HashSet<PlateProcessControlBO>(0);
	private Set<PlateDesignDetailBO> platedesigndetails = new HashSet<PlateDesignDetailBO>(0);
	private Set<AggSectionResultBO> aggsectionresults = new HashSet<AggSectionResultBO>(0);
	private Set<AggMarkerResultBO> aggmarkerresults = new HashSet<AggMarkerResultBO>(0);
	private Set<QcCriteriaStepResultBO> qccriteriastepresults = new HashSet<QcCriteriaStepResultBO>(0);

	public PlateSectionBO() {
	}

	public PlateSectionBO(long id, PlateDesignBO platedesign, String name) {
		this.id = id;
		this.platedesign = platedesign;
		this.name = name;
	}

	public PlateSectionBO(long id, PlateDesignBO platedesign, String name,
			Set<QcResultFinalBO> qcresultfinals, Set<PlateDesignDetailBO> platedesigndetails, Set<AggMarkerResultBO> aggmarkerresults,
			Set<QcCriteriaStepResultBO> qccriteriastepresults) {
		this.id = id;
		this.platedesign = platedesign;
		this.name = name;
		this.qcresultfinals = qcresultfinals;
		this.platedesigndetails = platedesigndetails;
		this.aggmarkerresults = aggmarkerresults;
		this.qccriteriastepresults = qccriteriastepresults;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateDesignBO getPlatedesign() {
		return this.platedesign;
	}

	public void setPlatedesign(PlateDesignBO platedesign) {
		this.platedesign = platedesign;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<AggregateBO> getAggregates() {
		return this.aggregates;
	}

	public void setAggregates(Set<AggregateBO> aggregates) {
		this.aggregates = aggregates;
	}

	public Set<QcResultFinalBO> getQcresultfinals() {
		return this.qcresultfinals;
	}

	public void setQcresultfinals(Set<QcResultFinalBO> qcresultfinals) {
		this.qcresultfinals = qcresultfinals;
	}

	public Set<PlateProcessControlBO> getPlateprocesscontrols() {
		return this.plateprocesscontrols;
	}

	public void setPlateprocesscontrols(Set<PlateProcessControlBO> plateprocesscontrols) {
		this.plateprocesscontrols = plateprocesscontrols;
	}

	public Set<PlateDesignDetailBO> getPlatedesigndetails() {
		return this.platedesigndetails;
	}

	public void setPlatedesigndetails(Set<PlateDesignDetailBO> platedesigndetails) {
		this.platedesigndetails = platedesigndetails;
	}

	public Set<AggSectionResultBO> getAggsectionresults() {
		return this.aggsectionresults;
	}

	public void setAggsectionresults(Set<AggSectionResultBO> aggsectionresults) {
		this.aggsectionresults = aggsectionresults;
	}

	public Set<AggMarkerResultBO> getAggmarkerresults() {
		return this.aggmarkerresults;
	}

	public void setAggmarkerresults(Set<AggMarkerResultBO> aggmarkerresults) {
		this.aggmarkerresults = aggmarkerresults;
	}

	public Set<QcCriteriaStepResultBO> getQccriteriastepresults() {
		return this.qccriteriastepresults;
	}

	public void setQccriteriastepresults(Set<QcCriteriaStepResultBO> qccriteriastepresults) {
		this.qccriteriastepresults = qccriteriastepresults;
	}

}
