package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessElementCategoryBO generated by hbm2java
 */
public class ProcessElementCategoryBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String name;
	private Set<ProcessElementBO> processelements = new HashSet<ProcessElementBO>(0);

	public ProcessElementCategoryBO() {
	}

	public ProcessElementCategoryBO(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public ProcessElementCategoryBO(int id, String name, Set<ProcessElementBO> processelements) {
		this.id = id;
		this.name = name;
		this.processelements = processelements;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<ProcessElementBO> getProcesselements() {
		return this.processelements;
	}

	public void setProcesselements(Set<ProcessElementBO> processelements) {
		this.processelements = processelements;
	}

}
