package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * QcCriteriaStepResultBO generated by hbm2java
 */
public class ProcessControlDetailResultBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlDetailBO processControlDetail;
	private PlateSetBO plateSet;
	private PlateSectionBO plateSection;
	private Boolean pass;
	private String failureReason;

	public ProcessControlDetailResultBO() {
	}

	public ProcessControlDetailResultBO(long id, ProcessControlDetailBO processControlDetail,
			PlateSetBO plateSet, PlateSectionBO plateSection) {
		this.id = id;
		this.processControlDetail = processControlDetail;
		this.plateSet = plateSet;
		this.plateSection = plateSection;
	}

	public ProcessControlDetailResultBO(long id, ProcessControlDetailBO processControlDetail,
			PlateSetBO plateSet, PlateSectionBO plateSection, Boolean pass,
			String failureReason) {
		this.id = id;
		this.processControlDetail = processControlDetail;
		this.plateSet = plateSet;
		this.plateSection = plateSection;
		this.pass = pass;
		this.failureReason = failureReason;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlDetailBO getProcessControlDetail() {
		return this.processControlDetail;
	}

	public void setProcessControlDetail(ProcessControlDetailBO processControlDetail) {
		this.processControlDetail = processControlDetail;
	}

	public PlateSetBO getPlateSet() {
		return this.plateSet;
	}

	public void setPlateSet(PlateSetBO plateSet) {
		this.plateSet = plateSet;
	}

	public PlateSectionBO getPlateSection() {
		return this.plateSection;
	}

	public void setPlateSection(PlateSectionBO plateSection) {
		this.plateSection = plateSection;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	public String getFailureReason() {
		return this.failureReason;
	}

	public void setFailureReason(String failureReason) {
		this.failureReason = failureReason;
	}

}
