package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * Processcontroldetail generated by hbm2java
 */
public class ProcessControlDetailBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlBO processControl;
	private MarkerBO marker;
	private double expectedValue;
	private double bound;
	private String lot;
	
	public ProcessControlDetailBO() {
	}

	public ProcessControlDetailBO(long id, ProcessControlBO processcontrol,
			MarkerBO marker, double expectedvalue, String lot) {
		this.id = id;
		this.processControl = processcontrol;
		this.marker = marker;
		this.expectedValue = expectedvalue;
		this.lot = lot;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlBO getProcessControl() {
		return this.processControl;
	}

	public void setProcessControl(ProcessControlBO processcontrol) {
		this.processControl = processcontrol;
	}

	public MarkerBO getMarker() {
		return this.marker;
	}

	public void setMarker(MarkerBO marker) {
		this.marker = marker;
	}

	public double getExpectedValue() {
		return this.expectedValue;
	}

	public void setExpectedValue(double expectedvalue) {
		this.expectedValue = expectedvalue;
	}

	/**
	 * @return the standardDeviation
	 */
	public double getBound() {
		return bound;
	}

	/**
	 * @param standardDeviation the standardDeviation to set
	 */
	public void setBound(double bound) {
		this.bound = bound;
	}

	/**
	 * @return the lot
	 */
	public String getLot() {
		return lot;
	}

	/**
	 * @param lot the lot to set
	 */
	public void setLot(String lot) {
		this.lot = lot;
	}

}
