package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * QcCriteriaStepResultBO generated by hbm2java
 */
public class ProcessControlRawScoreResultBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlRawScoreBO processControlRawScore;
	private PlateSetBO plateSet;
	private PlateSectionBO plateSection;
	private Boolean pass;
	private String failureReason;

	public ProcessControlRawScoreResultBO() {
	}

	public ProcessControlRawScoreResultBO(long id, ProcessControlRawScoreBO processControlRawScore,
			PlateSetBO plateset, PlateSectionBO platesection) {
		this.id = id;
		this.processControlRawScore = processControlRawScore;
		this.plateSet = plateset;
		this.plateSection = platesection;
	}

	public ProcessControlRawScoreResultBO(long id, ProcessControlRawScoreBO processControlRawScore,
			PlateSetBO plateset, PlateSectionBO platesection, Boolean pass,
			String resultvalue) {
		this.id = id;
		this.processControlRawScore = processControlRawScore;
		this.plateSet = plateset;
		this.plateSection = platesection;
		this.pass = pass;
		this.failureReason = resultvalue;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlRawScoreBO getProcessControlRawScore() {
		return this.processControlRawScore;
	}

	public void setProcessControlRawScore(ProcessControlRawScoreBO qccriteriastep) {
		this.processControlRawScore = qccriteriastep;
	}

	public PlateSetBO getPlateSet() {
		return this.plateSet;
	}

	public void setPlateSet(PlateSetBO plateset) {
		this.plateSet = plateset;
	}

	public PlateSectionBO getPlateSection() {
		return this.plateSection;
	}

	public void setPlateSection(PlateSectionBO platesection) {
		this.plateSection = platesection;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	public String getFailureReason() {
		return this.failureReason;
	}

	public void setFailureReason(String resultvalue) {
		this.failureReason = resultvalue;
	}

}
