package com.xdx.sax.bo;

import java.io.Serializable;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

/**
 * ProcessStepBO generated by hbm2java
 */
public class ProcessStepBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessElementBO processelement;
	private ProcessBO process;
	private long steporder;

	public ProcessStepBO() {
	}

	public ProcessStepBO(long id, ProcessElementBO processelement, ProcessBO process,
			long steporder) {
		this.id = id;
		this.processelement = processelement;
		this.process = process;
		this.steporder = steporder;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessElementBO getProcesselement() {
		return this.processelement;
	}

	public void setProcesselement(ProcessElementBO processelement) {
		this.processelement = processelement;
	}

	public ProcessBO getProcess() {
		return this.process;
	}

	public void setProcess(ProcessBO process) {
		this.process = process;
	}

	public long getSteporder() {
		return this.steporder;
	}

	public void setSteporder(long steporder) {
		this.steporder = steporder;
	}

}
