package com.xdx.sax.bo;

// Generated Feb 13, 2009 8:27:50 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Processcontrol generated by hbm2java
 */
public class ProcessControlBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private TestcodeBO testcode;
	private String externalid;
	private Set<ProcessControlDetailBO> processcontroldetails = new HashSet<ProcessControlDetailBO>(0);
	private Set<PlateProcessControlBO> plateprocesscontrols = new HashSet<PlateProcessControlBO>(0);

	public ProcessControlBO() {
	}

	public ProcessControlBO(long id, TestcodeBO testcode, String externalid) {
		this.id = id;
		this.testcode = testcode;
		this.externalid = externalid;
	}

	public ProcessControlBO(long id, TestcodeBO testcode, String externalid,
			Set<ProcessControlDetailBO> processcontroldetails, Set<PlateProcessControlBO> plateprocesscontrols) {
		this.id = id;
		this.testcode = testcode;
		this.externalid = externalid;
		this.processcontroldetails = processcontroldetails;
		this.plateprocesscontrols = plateprocesscontrols;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TestcodeBO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeBO testcode) {
		this.testcode = testcode;
	}

	public String getExternalid() {
		return this.externalid;
	}

	public void setExternalid(String externalid) {
		this.externalid = externalid;
	}

	public Set<ProcessControlDetailBO> getProcesscontroldetails() {
		return this.processcontroldetails;
	}

	public void setProcesscontroldetails(Set<ProcessControlDetailBO> processcontroldetails) {
		this.processcontroldetails = processcontroldetails;
	}

	public Set<PlateProcessControlBO> getPlateprocesscontrols() {
		return this.plateprocesscontrols;
	}

	public void setPlateprocesscontrols(Set<PlateProcessControlBO> plateprocesscontrols) {
		this.plateprocesscontrols = plateprocesscontrols;
	}

}
