package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessBO generated by hbm2java
 */
public class ProcessBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private TestcodeBO testcode;
	private String name;
	private boolean isactive;
	private long createdbyuserid;
	private Date createddate;
	private Set<ProcessStepBO> processsteps = new HashSet<ProcessStepBO>(0);

	public ProcessBO() {
	}

	public ProcessBO(long id, TestcodeBO testcode, String name, boolean isactive,
			long createdbyuserid, Date createddate) {
		this.id = id;
		this.testcode = testcode;
		this.name = name;
		this.isactive = isactive;
		this.createdbyuserid = createdbyuserid;
		this.createddate = createddate;
	}

	public ProcessBO(long id, TestcodeBO testcode, String name, boolean isactive,
			long createdbyuserid, Date createddate, Set<ProcessStepBO> processsteps) {
		this.id = id;
		this.testcode = testcode;
		this.name = name;
		this.isactive = isactive;
		this.createdbyuserid = createdbyuserid;
		this.createddate = createddate;
		this.processsteps = processsteps;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TestcodeBO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeBO testcode) {
		this.testcode = testcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	public long getCreatedbyuserid() {
		return this.createdbyuserid;
	}

	public void setCreatedbyuserid(long createdbyuserid) {
		this.createdbyuserid = createdbyuserid;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Set<ProcessStepBO> getProcesssteps() {
		return this.processsteps;
	}

	public void setProcesssteps(Set<ProcessStepBO> processsteps) {
		this.processsteps = processsteps;
	}

}
