package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessElementBO generated by hbm2java
 */
public class ProcessElementBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessElementCategoryBO processelementcategory;
	private String name;
	private String classname;
	private Set<ProcessStepBO> processsteps = new HashSet<ProcessStepBO>(0);

	public ProcessElementBO() {
	}

	public ProcessElementBO(long id,
			ProcessElementCategoryBO processelementcategory, String name,
			String class_) {
		this.id = id;
		this.processelementcategory = processelementcategory;
		this.name = name;
		this.classname = class_;
	}

	public ProcessElementBO(long id,
			ProcessElementCategoryBO processelementcategory, String name,
			String class_, Set<ProcessStepBO> processsteps) {
		this.id = id;
		this.processelementcategory = processelementcategory;
		this.name = name;
		this.classname = class_;
		this.processsteps = processsteps;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessElementCategoryBO getProcesselementcategory() {
		return this.processelementcategory;
	}

	public void setProcesselementcategory(
			ProcessElementCategoryBO processelementcategory) {
		this.processelementcategory = processelementcategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public Set<ProcessStepBO> getProcesssteps() {
		return this.processsteps;
	}

	public void setProcesssteps(Set<ProcessStepBO> processsteps) {
		this.processsteps = processsteps;
	}

}
