package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * QcCriteriaStepResultBO generated by hbm2java
 */
public class QcCriteriaStepResultBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private QcCriteriaStepBO qccriteriastep;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private Boolean pass;
	private Boolean isBorderline;
	private String resultvalue;

	public QcCriteriaStepResultBO() {
	}

	public QcCriteriaStepResultBO(long id, QcCriteriaStepBO qccriteriastep,
			PlateSetBO plateset, PlateSectionBO platesection) {
		this.id = id;
		this.qccriteriastep = qccriteriastep;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public QcCriteriaStepResultBO(long id, QcCriteriaStepBO qccriteriastep,
			PlateSetBO plateset, PlateSectionBO platesection, Boolean pass,
			String resultvalue) {
		this.id = id;
		this.qccriteriastep = qccriteriastep;
		this.plateset = plateset;
		this.platesection = platesection;
		this.pass = pass;
		this.resultvalue = resultvalue;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QcCriteriaStepBO getQccriteriastep() {
		return this.qccriteriastep;
	}

	public void setQccriteriastep(QcCriteriaStepBO qccriteriastep) {
		this.qccriteriastep = qccriteriastep;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	public Boolean getIsBorderline() {
		return isBorderline;
	}

	public void setIsBorderline(Boolean isBorderline) {
		this.isBorderline = isBorderline;
	}

	public String getResultvalue() {
		return this.resultvalue;
	}

	public void setResultvalue(String resultvalue) {
		this.resultvalue = resultvalue;
	}

}
