package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * QcCriteriaStepBO generated by hbm2java
 */
public class QcCriteriaStepBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private QcCriteriaStepTemplateBO qccriteriasteptemplate;
	private QcCriteriaBO qccriteria;
	private long ranking;
	private String passreturnresult;
	private String failreturnresult;
	private String assay1sub;
	private String assay2sub;
	private String yvalsub;
	private String zvalsub;
	private String processorStatus;
	private String normalizationClass;
	private Set<QcCriteriaStepResultBO> qccriteriastepresults = new HashSet<QcCriteriaStepResultBO>(0);

	public QcCriteriaStepBO() {
	}

	public QcCriteriaStepBO(long id,
			QcCriteriaStepTemplateBO qccriteriasteptemplate,
			QcCriteriaBO qccriteria, long ranking) {
		this.id = id;
		this.qccriteriasteptemplate = qccriteriasteptemplate;
		this.qccriteria = qccriteria;
		this.ranking = ranking;
	}

	public QcCriteriaStepBO(long id,
			QcCriteriaStepTemplateBO qccriteriasteptemplate,
			QcCriteriaBO qccriteria, long ranking, String passreturnresult, String failreturnresult,
			String assay1sub, String assay2sub, String yvalsub, String zvalsub,
			String returnedfailstatus, String nulldataaction,
			Set<QcCriteriaStepResultBO> qccriteriastepresults) {
		this.id = id;
		this.qccriteriasteptemplate = qccriteriasteptemplate;
		this.qccriteria = qccriteria;
		this.ranking = ranking;
		this.passreturnresult = passreturnresult;
		this.failreturnresult = failreturnresult;
		this.assay1sub = assay1sub;
		this.assay2sub = assay2sub;
		this.yvalsub = yvalsub;
		this.zvalsub = zvalsub;
		this.processorStatus = returnedfailstatus;
		this.normalizationClass = nulldataaction;
		this.qccriteriastepresults = qccriteriastepresults;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QcCriteriaStepTemplateBO getQccriteriasteptemplate() {
		return this.qccriteriasteptemplate;
	}

	public void setQccriteriasteptemplate(
			QcCriteriaStepTemplateBO qccriteriasteptemplate) {
		this.qccriteriasteptemplate = qccriteriasteptemplate;
	}

	public QcCriteriaBO getQccriteria() {
		return this.qccriteria;
	}

	public void setQccriteria(QcCriteriaBO qccriteria) {
		this.qccriteria = qccriteria;
	}

	public long getRanking() {
		return this.ranking;
	}

	public void setRanking(long ranking) {
		this.ranking = ranking;
	}

	public String getPassreturnresult() {
		return this.passreturnresult;
	}

	public void setPassreturnresult(String passreturnresult) {
		this.passreturnresult = passreturnresult;
	}

	public String getFailreturnresult() {
		return this.failreturnresult;
	}

	public void setFailreturnresult(String failreturnresult) {
		this.failreturnresult = failreturnresult;
	}

	public String getAssay1sub() {
		return this.assay1sub;
	}

	public void setAssay1sub(String assay1sub) {
		this.assay1sub = assay1sub;
	}

	public String getAssay2sub() {
		return this.assay2sub;
	}

	public void setAssay2sub(String assay2sub) {
		this.assay2sub = assay2sub;
	}

	public String getYvalsub() {
		return this.yvalsub;
	}

	public void setYvalsub(String yvalsub) {
		this.yvalsub = yvalsub;
	}

	public String getZvalsub() {
		return this.zvalsub;
	}

	public void setZvalsub(String zvalsub) {
		this.zvalsub = zvalsub;
	}

	public String getProcessorStatus() {
		return this.processorStatus;
	}

	public void setProcessorStatus(String processorStatus) {
		this.processorStatus = processorStatus;
	}

	public String getNormalizationClass() {
		return this.normalizationClass;
	}

	public void setNormalizationClass(String normalizationClass) {
		this.normalizationClass = normalizationClass;
	}

	public Set<QcCriteriaStepResultBO> getQccriteriastepresults() {
		return this.qccriteriastepresults;
	}

	public void setQccriteriastepresults(Set<QcCriteriaStepResultBO> qccriteriastepresults) {
		this.qccriteriastepresults = qccriteriastepresults;
	}

}
