package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * QcCriteriaStepTemplateBO generated by hbm2java
 */
public class QcCriteriaStepTemplateBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private String templatestring;
	private Set<QcCriteriaStepBO> qccriteriasteps = new HashSet<QcCriteriaStepBO>(0);
	private String classname;
	
	public QcCriteriaStepTemplateBO() {
	}

	public QcCriteriaStepTemplateBO(long id, String name,
			String templatestring, String classname) {
		this.id = id;
		this.name = name;
		this.templatestring = templatestring;
		this.classname = classname;
	}

	public QcCriteriaStepTemplateBO(long id, String name,
			String templatestring, Set<QcCriteriaStepBO> qccriteriasteps, String classname) {
		this.id = id;
		this.name = name;
		this.templatestring = templatestring;
		this.qccriteriasteps = qccriteriasteps;
		this.classname = classname;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTemplatestring() {
		return this.templatestring;
	}

	public void setTemplatestring(String templatestring) {
		this.templatestring = templatestring;
	}

	public Set<QcCriteriaStepBO> getQccriteriasteps() {
		return this.qccriteriasteps;
	}

	public void setQccriteriasteps(Set<QcCriteriaStepBO> qccriteriasteps) {
		this.qccriteriasteps = qccriteriasteps;
	}

	/**
	 * @return the classname
	 */
	public String getClassname() {
		return classname;
	}

	/**
	 * @param classname the classname to set
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}

}
