package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * QcCriteriaBO generated by hbm2java
 */
public class QcCriteriaBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private QcSchemaBO qcschema;
	private long ranking;
	private String criterianame;
	private String elementdesc;
	private Set<QcCriteriaStepBO> qccriteriasteps = new HashSet<QcCriteriaStepBO>(0);

	public QcCriteriaBO() {
	}

	public QcCriteriaBO(long id, QcSchemaBO qcschema, long ranking,
			String criterianame) {
		this.id = id;
		this.qcschema = qcschema;
		this.ranking = ranking;
		this.criterianame = criterianame;
	}

	public QcCriteriaBO(long id, QcSchemaBO qcschema,
			long ranking, String criterianame,
			String elementdesc, Set<QcCriteriaStepBO> qccriteriasteps) {
		this.id = id;
		this.qcschema = qcschema;
		this.ranking = ranking;
		this.criterianame = criterianame;
		this.elementdesc = elementdesc;
		this.qccriteriasteps = qccriteriasteps;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QcSchemaBO getQcschema() {
		return this.qcschema;
	}

	public void setQcschema(QcSchemaBO qcschema) {
		this.qcschema = qcschema;
	}

	public long getRanking() {
		return this.ranking;
	}

	public void setRanking(long ranking) {
		this.ranking = ranking;
	}

	public String getCriterianame() {
		return this.criterianame;
	}

	public void setCriterianame(String criterianame) {
		this.criterianame = criterianame;
	}

	public String getElementdesc() {
		return this.elementdesc;
	}

	public void setElementdesc(String elementdesc) {
		this.elementdesc = elementdesc;
	}

	public Set<QcCriteriaStepBO> getQccriteriasteps() {
		return this.qccriteriasteps;
	}

	public void setQccriteriasteps(Set<QcCriteriaStepBO> qccriteriasteps) {
		this.qccriteriasteps = qccriteriasteps;
	}

}
