package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;

/**
 * QcResultFinalBO generated by hbm2java
 */
@SuppressWarnings("serial")
public class QcResultFinalBO implements java.io.Serializable {

	private long id;
	private PlateSetBO plateset;
	private PlateSectionBO platesection;
	private String saxqcresult;
	private String userqcresult;
	private String qcFailReason;
	private String createdby;
	private Date createddate;

	public QcResultFinalBO() {
	}

	public QcResultFinalBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public QcResultFinalBO(long id, PlateSetBO plateset,
			PlateSectionBO platesection, String saxqcresult, String userqcresult,
			String qcFailReason, String createdby, Date createddate) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.saxqcresult = saxqcresult;
		this.userqcresult = userqcresult;
		this.qcFailReason = qcFailReason;
		this.createdby = createdby;
		this.createddate = createddate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetBO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetBO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionBO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionBO platesection) {
		this.platesection = platesection;
	}

	public String getSaxqcresult() {
		return this.saxqcresult;
	}

	public void setSaxqcresult(String saxqcresult) {
		this.saxqcresult = saxqcresult;
	}

	public String getUserqcresult() {
		return this.userqcresult;
	}

	public void setUserqcresult(String userqcresult) {
		this.userqcresult = userqcresult;
	}

	/**
	 * @return the qcFailReason
	 */
	public String getQcFailReason() {
		return qcFailReason;
	}

	/**
	 * @param qcFailReason the qcFailReason to set
	 */
	public void setQcFailReason(String qcFailReason) {
		this.qcFailReason = qcFailReason;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

}
