package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QcSchemaBO generated by hbm2java
 */
public class QcSchemaBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String schemaname;
	private Date createdate;
	private String creator;
	private Date modifydate;
	private String modifier;
	private Set<QcCriteriaBO> qccriterias = new HashSet<QcCriteriaBO>(0);
	private Set<TestcodeBO> testcodes = new HashSet<TestcodeBO>(0);

	public QcSchemaBO() {
	}

	public QcSchemaBO(long schemaid) {
		this.id = schemaid;
	}

	public QcSchemaBO(long schemaid, String schemaname, Date createdate,
			String creator, Date modifydate, String modifier, Set<QcCriteriaBO> qccriterias,
			Set<TestcodeBO> testcodes) {
		this.id = schemaid;
		this.schemaname = schemaname;
		this.createdate = createdate;
		this.creator = creator;
		this.modifydate = modifydate;
		this.modifier = modifier;
		this.qccriterias = qccriterias;
		this.testcodes = testcodes;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long schemaid) {
		this.id = schemaid;
	}

	public String getSchemaname() {
		return this.schemaname;
	}

	public void setSchemaname(String schemaname) {
		this.schemaname = schemaname;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Set<QcCriteriaBO> getQccriterias() {
		return this.qccriterias;
	}

	public void setQccriterias(Set<QcCriteriaBO> qccriterias) {
		this.qccriterias = qccriterias;
	}

	public Set<TestcodeBO> getTestcodes() {
		return this.testcodes;
	}

	public void setTestcodes(Set<TestcodeBO> testcodes) {
		this.testcodes = testcodes;
	}

}
