package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * RawWellDataBO generated by hbm2java
 */
public class RawWellDataBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateBO plate;
	private AggregateBO aggregate;
	private WellTypeBO wellType;
	private WellRnBO[] rn;
	private long rownumber;
	private long columnnumber;
	private Integer loglinearleftend;
	private Integer loglinearrightend;
	private int errornum;
	private Double deltact;
	private Double bkgfam;
	private Double baselinefam;
	private Double saturationfam;
	private Double widthmetric;
	private Double ambiguitymetric;
	private Double xdxct;
	private Double cterror;
	private Double normalizedXdxCt;
	private boolean isEmpty;
	private Set<MarkerBO> markers = new HashSet<MarkerBO>(0);
	
	public RawWellDataBO() {
	}

	public RawWellDataBO(long id, PlateBO plate, long rownumber,
			long columnnumber) {
		this.id = id;
		this.plate = plate;
		this.rownumber = rownumber;
		this.columnnumber = columnnumber;
	}

	public RawWellDataBO(long id, PlateBO plate, AggregateBO aggregate, 
			WellTypeBO wellType, long rownumber,
			long columnnumber, Integer loglinearleftend, Integer loglinearrightend,
			int errornum,
			Double deltact, Double bkgfam, Double baselinefam,
			Double saturationfam, Double widthmetric,
			Double ambiguitymetric, Double xdxct, Double cterror,
			Double normalizedCt, boolean isEmpty, Set<MarkerBO> markers) {
		this.id = id;
		this.plate = plate;
		this.aggregate = aggregate;
		this.wellType = wellType;
		this.rownumber = rownumber;
		this.columnnumber = columnnumber;
		this.loglinearleftend = loglinearleftend;
		this.loglinearrightend = loglinearrightend;
		this.errornum = errornum;
		this.deltact = deltact;
		this.bkgfam = bkgfam;
		this.baselinefam = baselinefam;
		this.saturationfam = saturationfam;
		this.widthmetric = widthmetric;
		this.ambiguitymetric = ambiguitymetric;
		this.xdxct = xdxct;
		this.cterror = cterror;
		this.normalizedXdxCt = normalizedCt;
		this.isEmpty = isEmpty;
		this.markers = markers;
	}

	public String toString() {
		String res = "ID = " + this.id;
		res = res + ", loglinearleftend = " + this.loglinearleftend;
		res = res + ", loglinearrightend = " + this.loglinearrightend;
		res = res + ", bkgfam = " + this.bkgfam;
		res = res + ", xdxct = " + this.xdxct;
		res = res + ", errornum = " + this.errornum;
		res = res + ", widthmetric = " + this.widthmetric;
		res = res + ", ambiguitymetric = " + this.ambiguitymetric;
		res = res + ", cterror = " + this.cterror;
		res = res + ", Markers = " + markers;
		return res;
	}
	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateBO getPlate() {
		return this.plate;
	}

	public void setPlate(PlateBO plate) {
		this.plate = plate;
	}

	public AggregateBO getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(AggregateBO aggregate) {
		this.aggregate = aggregate;
	}

	public WellTypeBO getWellType() {
		return this.wellType;
	}

	public void setWellType(WellTypeBO wellType) {
		this.wellType = wellType;
	}

	public WellRnBO[] getRn() {
		return rn;
	}

	public void setRn(WellRnBO[] rn) {
		this.rn = rn;
	}

	public long getRownumber() {
		return this.rownumber;
	}

	public void setRownumber(long i) {
		this.rownumber = i;
	}

	public long getColumnnumber() {
		return this.columnnumber;
	}

	public void setColumnnumber(long j) {
		this.columnnumber = j;
	}

	public Integer getLoglinearleftend() {
		return this.loglinearleftend;
	}

	public void setLoglinearleftend(Integer loglinearleftend) {
		this.loglinearleftend = loglinearleftend;
	}

	public Integer getLoglinearrightend() {
		return this.loglinearrightend;
	}

	public void setLoglinearrightend(Integer loglinearrightend) {
		this.loglinearrightend = loglinearrightend;
	}

	public int getErrornum() {
		return this.errornum;
	}

	public void setErrornum(int errornum) {
		this.errornum = errornum;
	}

	public Double getDeltact() {
		return this.deltact;
	}

	public void setDeltact(Double deltact) {
		this.deltact = deltact;
	}

	public Double getBkgfam() {
		return this.bkgfam;
	}

	public void setBkgfam(Double bkgfam) {
		this.bkgfam = bkgfam;
	}

	public Double getBaselinefam() {
		return this.baselinefam;
	}

	public void setBaselinefam(Double baselinefam) {
		this.baselinefam = baselinefam;
	}

	public Double getSaturationfam() {
		return this.saturationfam;
	}

	public void setSaturationfam(Double saturationfam) {
		this.saturationfam = saturationfam;
	}

	public Double getWidthmetric() {
		return this.widthmetric;
	}

	public void setWidthmetric(Double d) {
		if (d != null && d.isNaN())
			d = null;
		this.widthmetric = d;
	}

	public Double getAmbiguitymetric() {
		return this.ambiguitymetric;
	}

	public void setAmbiguitymetric(Double d) {
		if(d != null && d.isNaN())
			d = null;
		this.ambiguitymetric = d;
	}

	public Double getXdxct() {
		return this.xdxct;
	}

	public void setXdxct(Double d) {
		if (d != null && d.isNaN())
			d = null;
		this.xdxct = d;
	}

	public Double getCterror() {
		return this.cterror;
	}

	public void setCterror(Double d) {
		if (d != null && d.isNaN())
			d = null;
		this.cterror = d;
	}

	public Double getNormalizedXdxCt() {
		return normalizedXdxCt;
	}

	public void setNormalizedXdxCt(Double d) {
		if (d != null && d.isNaN())
			d = null;
		this.normalizedXdxCt = d;
	}

	public boolean getIsEmpty() {
		return isEmpty;
	}

	public void setIsEmpty(boolean isEmpty) {
		this.isEmpty = isEmpty;
	}

	public Set<MarkerBO> getMarkers() {
		return this.markers;
	}

	public void setMarkers(Set<MarkerBO> markers) {
		this.markers = markers;
	}

}
