package com.xdx.sax.bo;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TestcodeBO generated by hbm2java
 */
public class TestcodeBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String testcodename;
	private String testdescription;
	private QcSchemaBO qcSchema;
	private ProcessBO process;
	private Set<ConfigBO> configs = new HashSet<ConfigBO>(0);
	private Set<ProcessControlBO> processcontrols = new HashSet<ProcessControlBO>(0);
	private Set<PlateDesignBO> platedesigns = new HashSet<PlateDesignBO>(0);
	private Set<PlateSetBO> platesets = new HashSet<PlateSetBO>(0);
	
	public TestcodeBO() {
	}

	public TestcodeBO(long id, String testcodename, String testdescription) {
		this.id = id;
		this.testcodename = testcodename;
		this.testdescription = testdescription;
	}

	public TestcodeBO(long id, String testcodename, String testdescription, QcSchemaBO qcSchema,
			ProcessBO process, Set<ConfigBO> configs,
			Set<PlateDesignBO> platedesigns, Set<PlateSetBO> platesets) {
		this.id = id;
		this.testcodename = testcodename;
		this.testdescription = testdescription;
		this.qcSchema = qcSchema;
		this.process = process;
		this.configs = configs;
		this.platedesigns = platedesigns;
		this.platesets = platesets;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTestcodename() {
		return this.testcodename;
	}

	public void setTestcodename(String testcodename) {
		this.testcodename = testcodename;
	}

	public String getTestdescription() {
		return this.testdescription;
	}

	public void setTestdescription(String testdescription) {
		this.testdescription = testdescription;
	}

	public QcSchemaBO getQcSchema() {
		return this.qcSchema;
	}

	public void setQcSchema(QcSchemaBO qcSchema) {
		this.qcSchema = qcSchema;
	}

	/**
	 * @return the process
	 */
	public ProcessBO getProcess() {
		return process;
	}

	/**
	 * @param process the process to set
	 */
	public void setProcess(ProcessBO process) {
		this.process = process;
	}

	public Set<ConfigBO> getConfigs() {
		return this.configs;
	}

	public void setConfigs(Set<ConfigBO> configs) {
		this.configs = configs;
	}

	public Set<ProcessControlBO> getProcesscontrols() {
		return this.processcontrols;
	}

	public void setProcesscontrols(Set<ProcessControlBO> processcontrols) {
		this.processcontrols = processcontrols;
	}

	public Set<PlateDesignBO> getPlatedesigns() {
		return this.platedesigns;
	}

	public void setPlatedesigns(Set<PlateDesignBO> platedesigns) {
		this.platedesigns = platedesigns;
	}

	public Set<PlateSetBO> getPlatesets() {
		return this.platesets;
	}

	public void setPlatesets(Set<PlateSetBO> platesets) {
		this.platesets = platesets;
	}

}
