package com.xdx.sax.bo;

import java.io.Serializable;

/**
 * MarkerTypeBO generated by hbm2java
 */
public class WellTypeBO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;

	public WellTypeBO() {
	}

	public WellTypeBO(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
