package com.xdx.sax.bo;

//Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * WellRnBO generated by hbm2java
 */
public class WellRnBO implements Serializable {
	
	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private Double rn;

	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * @return the rn
	 */
	public Double getRn() {
		return rn;
	}

	/**
	 * @param rn the rn to set
	 */
	public void setRn(Double rn) {
		this.rn = rn;
	}
	
}
