package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * AggMarkerResultBO generated by hbm2java
 */
public class AggMarkerResultTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetTO plateset;
	private PlateSectionTO platesection;
	private AggregateTO aggregate;
	private Double wsmxdxct;
	private Double wsmnormct;
	private Double medianxdxct;
	private Double platestddev;
	private Double wsmBaselineFam;
	private Double wsmSaturationFam;
	private String errortype;

	public AggMarkerResultTO() {
	}

	public AggMarkerResultTO(long id, PlateSetTO plateset,
			PlateSectionTO platesection) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public AggMarkerResultTO(long id, PlateSetTO plateset,
			PlateSectionTO platesection, AggregateTO aggregate, 
			Double wsmxdxct, Double wsmnormct,
			Double medianxdxct, Double platestddev, 
			Double wsmBaselineFam, Double wsmSaturationFam,
			String errortype) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.aggregate = aggregate;
		this.wsmxdxct = wsmxdxct;
		this.wsmnormct = wsmnormct;
		this.medianxdxct = medianxdxct;
		this.platestddev = platestddev;
		this.wsmBaselineFam = wsmBaselineFam;
		this.wsmSaturationFam = wsmSaturationFam;
		this.errortype = errortype;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetTO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetTO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionTO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionTO platesection) {
		this.platesection = platesection;
	}

	public AggregateTO getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(AggregateTO aggregate) {
		this.aggregate = aggregate;
	}

	public Double getWsmxdxct() {
		return this.wsmxdxct;
	}

	public void setWsmxdxct(Double wsmxdxct) {
		this.wsmxdxct = wsmxdxct;
	}

	public Double getWsmnormct() {
		return this.wsmnormct;
	}

	public void setWsmnormct(Double wsmnormct) {
		this.wsmnormct = wsmnormct;
	}

	public Double getMedianxdxct() {
		return this.medianxdxct;
	}

	public void setMedianxdxct(Double medianxdxct) {
		this.medianxdxct = medianxdxct;
	}

	public Double getPlatestddev() {
		return this.platestddev;
	}

	public void setPlatestddev(Double platestddev) {
		this.platestddev = platestddev;
	}

	/**
	 * @return the wsmBaselineFam
	 */
	public Double getWsmBaselineFam() {
		return wsmBaselineFam;
	}

	/**
	 * @param wsmBaselineFam the wsmBaselineFam to set
	 */
	public void setWsmBaselineFam(Double wsmBaselineFam) {
		this.wsmBaselineFam = wsmBaselineFam;
	}

	/**
	 * @return the wsmSaturationFam
	 */
	public Double getWsmSaturationFam() {
		return wsmSaturationFam;
	}

	/**
	 * @param wsmSaturationFam the wsmSaturationFam to set
	 */
	public void setWsmSaturationFam(Double wsmSaturationFam) {
		this.wsmSaturationFam = wsmSaturationFam;
	}

	public String getErrortype() {
		return this.errortype;
	}

	public void setErrortype(String errortype) {
		this.errortype = errortype;
	}

}
