package com.xdx.sax.to;

import java.io.Serializable;

/**
 * ConfigBO generated by hbm2java
 */
public class AggregateTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private PlateSectionTO plateSection;

	public AggregateTO() {
	}

	public AggregateTO(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public PlateSectionTO getPlateSection() {
		return this.plateSection;
	}

	public void setPlateSection(PlateSectionTO plateSection) {
		this.plateSection = plateSection;
	}
}
