package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * ConfigBO generated by hbm2java
 */
public class ConfigTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private TestcodeTO testcode;
	private String name;
	private String value;
	private String configtype;

	public ConfigTO() {
	}

	public ConfigTO(long id, String name, String configtype) {
		this.id = id;
		this.name = name;
		this.configtype = configtype;
	}

	public ConfigTO(long id, TestcodeTO testcode, String name, String value,
			String configtype) {
		this.id = id;
		this.testcode = testcode;
		this.name = name;
		this.value = value;
		this.configtype = configtype;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TestcodeTO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeTO testcode) {
		this.testcode = testcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getConfigtype() {
		return this.configtype;
	}

	public void setConfigtype(String configtype) {
		this.configtype = configtype;
	}

}
