package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * MarkerBO generated by hbm2java
 */
public class MarkerTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private MarkerTypeTO markertype;
	private String name;

	public MarkerTO() {
	}

	public MarkerTO(long id, MarkerTypeTO markertype, String name) {
		this.id = id;
		this.markertype = markertype;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public MarkerTypeTO getMarkertype() {
		return this.markertype;
	}

	public void setMarkertype(MarkerTypeTO markertype) {
		this.markertype = markertype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
