package com.xdx.sax.to;

import java.io.Serializable;

/**
 * PlateDesignDetailBO generated by hbm2java
 */
public class PlateDesignDetailTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateDesignTO platedesign;
	private AggregateTO aggregate;
	private WellTypeTO wellType;
	private PlateSectionTO platesection;
	private long numberinset;
	private long platerow;
	private long platecolumn;

	public PlateDesignDetailTO() {
	}

	public PlateDesignDetailTO(long id, PlateDesignTO platedesign, 
			AggregateTO aggregate, WellTypeTO wellType,
			PlateSectionTO platesection, long numberinset,
			long platerow, long platecolumn) {
		this.id = id;
		this.platedesign = platedesign;
		this.aggregate = aggregate;
		this.wellType = wellType;
		this.platesection = platesection;
		this.numberinset = numberinset;
		this.platerow = platerow;
		this.platecolumn = platecolumn;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateDesignTO getPlatedesign() {
		return this.platedesign;
	}

	public void setPlatedesign(PlateDesignTO platedesign) {
		this.platedesign = platedesign;
	}

	public AggregateTO getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(AggregateTO aggregate) {
		this.aggregate = aggregate;
	}

	public WellTypeTO getWellType() {
		return this.wellType;
	}

	public void setWellType(WellTypeTO wellType) {
		this.wellType = wellType;
	}

	public PlateSectionTO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionTO platesection) {
		this.platesection = platesection;
	}

	public long getNumberinset() {
		return this.numberinset;
	}

	public void setNumberinset(long numberinset) {
		this.numberinset = numberinset;
	}

	public long getPlaterow() {
		return this.platerow;
	}

	public void setPlaterow(long platerow) {
		this.platerow = platerow;
	}

	public long getPlatecolumn() {
		return this.platecolumn;
	}

	public void setPlatecolumn(long platecolumn) {
		this.platecolumn = platecolumn;
	}

}
