package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * PlateSetBO generated by hbm2java
 */
public class PlateSetTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String externalId;
	private PlateDesignTO platedesign;
	private TestcodeTO testcode;
	private Date processedTimestamp;
	private Date registeredTimestamp;

	public PlateSetTO() {
	}

	public PlateSetTO(long id, String externalId, 
			PlateDesignTO platedesign, TestcodeTO testcode) {
		this.id = id;
		this.externalId = externalId;
		this.platedesign = platedesign;
		this.testcode = testcode;
	}

	public PlateSetTO(int id, PlateDesignTO platedesign, TestcodeTO testcode,
			Date processedTimestamp, Date registeredTimestamp) {
		this.id = id;
		this.platedesign = platedesign;
		this.testcode = testcode;
		this.processedTimestamp = processedTimestamp;
		this.registeredTimestamp = registeredTimestamp;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public PlateDesignTO getPlatedesign() {
		return this.platedesign;
	}

	public void setPlatedesign(PlateDesignTO platedesign) {
		this.platedesign = platedesign;
	}

	public TestcodeTO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeTO testcode) {
		this.testcode = testcode;
	}

	/**
	 * @return the processedTimestamp
	 */
	public Date getProcessedTimestamp() {
		return processedTimestamp;
	}

	/**
	 * @param processedTimestamp the processedTimestamp to set
	 */
	public void setProcessedTimestamp(Date processedTimestamp) {
		this.processedTimestamp = processedTimestamp;
	}

	/**
	 * @return the registeredTimestamp
	 */
	public Date getRegisteredTimestamp() {
		return registeredTimestamp;
	}

	/**
	 * @param registeredTimestamp the registeredTimestamp to set
	 */
	public void setRegisteredTimestamp(Date registeredTimestamp) {
		this.registeredTimestamp = registeredTimestamp;
	}

}
