package com.xdx.sax.to;

// Generated Feb 13, 2009 8:27:50 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * Plateprocesscontrol generated by hbm2java
 */
public class PlateProcessControlTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlTO processcontrol;
	private PlateSetTO plateset;
	private PlateSectionTO platesection;
	private Boolean isOk;
	private String failureReason;

	public PlateProcessControlTO() {
	}

	public PlateProcessControlTO(long id, ProcessControlTO processcontrol,
			PlateSetTO plateset, PlateSectionTO platesection) {
		this.id = id;
		this.processcontrol = processcontrol;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlTO getProcesscontrol() {
		return this.processcontrol;
	}

	public void setProcesscontrol(ProcessControlTO processcontrol) {
		this.processcontrol = processcontrol;
	}

	public PlateSetTO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetTO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionTO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionTO platesection) {
		this.platesection = platesection;
	}

	/**
	 * @return the isOk
	 */
	public Boolean getIsOk() {
		return isOk;
	}

	/**
	 * @param isOk the isOk to set
	 */
	public void setIsOk(Boolean isOk) {
		this.isOk = isOk;
	}

	/**
	 * @return the failureReason
	 */
	public String getFailureReason() {
		return failureReason;
	}

	/**
	 * @param failureReason the failureReason to set
	 */
	public void setFailureReason(String failureReason) {
		this.failureReason = failureReason;
	}

}
