package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PlateSectionBO generated by hbm2java
 */
public class PlateSectionTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateDesignTO platedesign;
	private String name;

	public PlateSectionTO() {
	}

	public PlateSectionTO(long id, PlateDesignTO platedesign, String name) {
		this.id = id;
		this.platedesign = platedesign;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateDesignTO getPlatedesign() {
		return this.platedesign;
	}

	public void setPlatedesign(PlateDesignTO platedesign) {
		this.platedesign = platedesign;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
