package com.xdx.sax.to;

import java.io.Serializable;

/**
 * PlateDesignBO generated by hbm2java
 */
public class PlateDesignTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private long numberofplates;
	private long numberrowsperplate;
	private long numbercolumnsperplate;
	private Double mastermixvolume; // IIL: ummVolume
	private Double availablewellvolume; // IIL: totalWellVolume

	public PlateDesignTO() {
	}

	public PlateDesignTO(long id, String name, long numberofplates,
			long numberrowsperplate, long numbercolumnsperplate) {
		this.id = id;
		this.name = name;
		this.numberofplates = numberofplates;
		this.numberrowsperplate = numberrowsperplate;
		this.numbercolumnsperplate = numbercolumnsperplate;
	}

	public PlateDesignTO(long id, String name, long numberofplates,
			long numberrowsperplate, long numbercolumnsperplate,
			Double mastermixvolume, Double availablewellvolume) {
		this.id = id;
		this.name = name;
		this.numberofplates = numberofplates;
		this.numberrowsperplate = numberrowsperplate;
		this.numbercolumnsperplate = numbercolumnsperplate;
		this.mastermixvolume = mastermixvolume;
		this.availablewellvolume = availablewellvolume;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getNumberofplates() {
		return this.numberofplates;
	}

	public void setNumberofplates(long numberofplates) {
		this.numberofplates = numberofplates;
	}

	public long getNumberrowsperplate() {
		return this.numberrowsperplate;
	}

	public void setNumberrowsperplate(long numberrowsperplate) {
		this.numberrowsperplate = numberrowsperplate;
	}

	public long getNumbercolumnsperplate() {
		return this.numbercolumnsperplate;
	}

	public void setNumbercolumnsperplate(long numbercolumnsperplate) {
		this.numbercolumnsperplate = numbercolumnsperplate;
	}

	public Double getMastermixvolume() {
		return this.mastermixvolume;
	}

	public void setMastermixvolume(Double mastermixvolume) {
		this.mastermixvolume = mastermixvolume;
	}

	public Double getAvailablewellvolume() {
		return this.availablewellvolume;
	}

	public void setAvailablewellvolume(Double availablewellvolume) {
		this.availablewellvolume = availablewellvolume;
	}

}
