package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * AggMarkerResultBO generated by hbm2java
 */
public class PlateSectionDetailTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateSetTO plateset;
	private PlateSectionTO platesection;
	private ProcessControlDetailTO processcontrol;
	private boolean isEmpty;

	public PlateSectionDetailTO() {
	}

	public PlateSectionDetailTO(long id, PlateSetTO plateset,
			PlateSectionTO platesection, boolean isEmpty) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.isEmpty = isEmpty;
	}

	public PlateSectionDetailTO(long id, PlateSetTO plateset,
			PlateSectionTO platesection, ProcessControlDetailTO processcontrol,
			boolean isEmpty) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.processcontrol = processcontrol;
		this.isEmpty = isEmpty;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateSetTO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetTO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionTO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionTO platesection) {
		this.platesection = platesection;
	}

	public ProcessControlDetailTO getProcesscontrol() {
		return this.processcontrol;
	}

	public void setProcesscontrol(ProcessControlDetailTO processcontrol) {
		this.processcontrol = processcontrol;
	}

	public boolean getIsEmpty() {
		return this.isEmpty;
	}

	public void setIsEmpty(boolean isEmpty) {
		this.isEmpty = isEmpty;
	}

}
