package com.xdx.sax.to;

// Generated Feb 13, 2009 8:27:50 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * Processcontroldetail generated by hbm2java
 */
public class ProcessControlDetailTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlTO processControl;
	private MarkerTO marker;
	private double expectedValue;
	private double bound;
	private String lot;

	public ProcessControlDetailTO() {
	}

	public ProcessControlDetailTO(long id, ProcessControlTO processcontrol,
			MarkerTO marker, double expectedvalue, String lot) {
		this.id = id;
		this.processControl = processcontrol;
		this.marker = marker;
		this.expectedValue = expectedvalue;
		this.lot = lot;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlTO getProcessControl() {
		return this.processControl;
	}

	public void setProcessControl(ProcessControlTO processcontrol) {
		this.processControl = processcontrol;
	}

	public MarkerTO getMarker() {
		return this.marker;
	}

	public void setMarker(MarkerTO marker) {
		this.marker = marker;
	}

	public double getExpectedValue() {
		return this.expectedValue;
	}

	public void setExpectedValue(double expectedvalue) {
		this.expectedValue = expectedvalue;
	}

	/**
	 * @return the standardDeviation
	 */
	public double getBound() {
		return bound;
	}

	/**
	 * @param standardDeviation the standardDeviation to set
	 */
	public void setBound(double standardDeviation) {
		this.bound = standardDeviation;
	}

	/**
	 * @return the lot
	 */
	public String getLot() {
		return lot;
	}

	/**
	 * @param lot the lot to set
	 */
	public void setLot(String lot) {
		this.lot = lot;
	}

}
