package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * ProcessBO generated by hbm2java
 */
public class ProcessTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private TestcodeTO testcode;
	private String name;
	private boolean isactive;
	private long createdbyuserid;
	private Date createddate;

	public ProcessTO() {
	}

	public ProcessTO(long id, TestcodeTO testcode, String name, boolean isactive,
			long createdbyuserid, Date createddate) {
		this.id = id;
		this.testcode = testcode;
		this.name = name;
		this.isactive = isactive;
		this.createdbyuserid = createdbyuserid;
		this.createddate = createddate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TestcodeTO getTestcode() {
		return this.testcode;
	}

	public void setTestcode(TestcodeTO testcode) {
		this.testcode = testcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	public long getCreatedbyuserid() {
		return this.createdbyuserid;
	}

	public void setCreatedbyuserid(long createdbyuserid) {
		this.createdbyuserid = createdbyuserid;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

}
