package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * ProcessElementCategoryBO generated by hbm2java
 */
public class ProcessElementCategoryTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String name;

	public ProcessElementCategoryTO() {
	}

	public ProcessElementCategoryTO(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
