package com.xdx.sax.to;

import java.io.Serializable;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

/**
 * ProcessStepBO generated by hbm2java
 */
public class ProcessStepTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessElementTO processelement;
	private ProcessTO process;
	private long steporder;

	public ProcessStepTO() {
	}

	public ProcessStepTO(long id, ProcessElementTO processelement, ProcessTO process,
			long steporder) {
		this.id = id;
		this.processelement = processelement;
		this.process = process;
		this.steporder = steporder;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessElementTO getProcesselement() {
		return this.processelement;
	}

	public void setProcesselement(ProcessElementTO processelement) {
		this.processelement = processelement;
	}

	public ProcessTO getProcess() {
		return this.process;
	}

	public void setProcess(ProcessTO process) {
		this.process = process;
	}

	public long getSteporder() {
		return this.steporder;
	}

	public void setSteporder(long steporder) {
		this.steporder = steporder;
	}

}
