package com.xdx.sax.to;

import java.io.Serializable;

/**
 * QcCriteriaStepResultBO generated by hbm2java
 */
public class ProcessControlRawScoreResultTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlRawScoreTO processControlRawScore;
	private PlateSetTO plateSet;
	private PlateSectionTO plateSection;
	private Boolean pass;
	private String failureReason;

	public ProcessControlRawScoreResultTO() {
	}

	public ProcessControlRawScoreResultTO(long id, ProcessControlRawScoreTO processControlRawScore,
			PlateSetTO plateset, PlateSectionTO platesection) {
		this.id = id;
		this.processControlRawScore = processControlRawScore;
		this.plateSet = plateset;
		this.plateSection = platesection;
	}

	public ProcessControlRawScoreResultTO(long id, ProcessControlRawScoreTO processControlRawScore,
			PlateSetTO plateset, PlateSectionTO platesection, Boolean pass,
			String resultvalue) {
		this.id = id;
		this.processControlRawScore = processControlRawScore;
		this.plateSet = plateset;
		this.plateSection = platesection;
		this.pass = pass;
		this.failureReason = resultvalue;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlRawScoreTO getProcessControlRawScore() {
		return this.processControlRawScore;
	}

	public void setProcessControlRawScore(ProcessControlRawScoreTO qccriteriastep) {
		this.processControlRawScore = qccriteriastep;
	}

	public PlateSetTO getPlateSet() {
		return this.plateSet;
	}

	public void setPlateSet(PlateSetTO plateset) {
		this.plateSet = plateset;
	}

	public PlateSectionTO getPlateSection() {
		return this.plateSection;
	}

	public void setPlateSection(PlateSectionTO platesection) {
		this.plateSection = platesection;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	public String getFailureReason() {
		return this.failureReason;
	}

	public void setFailureReason(String resultvalue) {
		this.failureReason = resultvalue;
	}

}
