package com.xdx.sax.to;

import java.io.Serializable;

/**
 * QcCriteriaStepResultBO generated by hbm2java
 */
public class ProcessControlDetailResultTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessControlDetailTO processControlDetail;
	private PlateSetTO plateSet;
	private PlateSectionTO plateSection;
	private Boolean pass;
	private String failureReason;

	public ProcessControlDetailResultTO() {
	}

	public ProcessControlDetailResultTO(long id, ProcessControlDetailTO processControlDetail,
			PlateSetTO plateSet, PlateSectionTO plateSection) {
		this.id = id;
		this.processControlDetail = processControlDetail;
		this.plateSet = plateSet;
		this.plateSection = plateSection;
	}

	public ProcessControlDetailResultTO(long id, ProcessControlDetailTO processControlDetail,
			PlateSetTO plateSet, PlateSectionTO plateSection, Boolean pass,
			String failureReason) {
		this.id = id;
		this.processControlDetail = processControlDetail;
		this.plateSet = plateSet;
		this.plateSection = plateSection;
		this.pass = pass;
		this.failureReason = failureReason;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessControlDetailTO getProcessControlDetail() {
		return this.processControlDetail;
	}

	public void setProcessControlDetail(ProcessControlDetailTO processControlDetail) {
		this.processControlDetail = processControlDetail;
	}

	public PlateSetTO getPlateSet() {
		return this.plateSet;
	}

	public void setPlateSet(PlateSetTO plateSet) {
		this.plateSet = plateSet;
	}

	public PlateSectionTO getPlateSection() {
		return this.plateSection;
	}

	public void setPlateSection(PlateSectionTO plateSection) {
		this.plateSection = plateSection;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	public String getFailureReason() {
		return this.failureReason;
	}

	public void setFailureReason(String failureReason) {
		this.failureReason = failureReason;
	}

}
