package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * ProcessElementBO generated by hbm2java
 */
public class ProcessElementTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private ProcessElementCategoryTO processelementcategory;
	private String name;
	private String class_;

	public ProcessElementTO() {
	}

	public ProcessElementTO(long id,
			ProcessElementCategoryTO processelementcategory, String name,
			String class_) {
		this.id = id;
		this.processelementcategory = processelementcategory;
		this.name = name;
		this.class_ = class_;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ProcessElementCategoryTO getProcesselementcategory() {
		return this.processelementcategory;
	}

	public void setProcesselementcategory(
			ProcessElementCategoryTO processelementcategory) {
		this.processelementcategory = processelementcategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

}
