package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * QcCriteriaBO generated by hbm2java
 */
public class QcCriteriaTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private QcSchemaTO qcschema;
	private long ranking;
	private String criterianame;
	private String elementdesc;

	public QcCriteriaTO() {
	}

	public QcCriteriaTO(long id, QcSchemaTO qcschema, long ranking,
			String criterianame) {
		this.id = id;
		this.qcschema = qcschema;
		this.ranking = ranking;
		this.criterianame = criterianame;
	}

	public QcCriteriaTO(long id, QcSchemaTO qcschema,
			long ranking, String criterianame, String elementdesc) {
		this.id = id;
		this.qcschema = qcschema;
		this.ranking = ranking;
		this.criterianame = criterianame;
		this.elementdesc = elementdesc;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QcSchemaTO getQcschema() {
		return this.qcschema;
	}

	public void setQcschema(QcSchemaTO qcschema) {
		this.qcschema = qcschema;
	}

	public long getRanking() {
		return this.ranking;
	}

	public void setRanking(long ranking) {
		this.ranking = ranking;
	}

	public String getCriterianame() {
		return this.criterianame;
	}

	public void setCriterianame(String criterianame) {
		this.criterianame = criterianame;
	}

	public String getElementdesc() {
		return this.elementdesc;
	}

	public void setElementdesc(String elementdesc) {
		this.elementdesc = elementdesc;
	}

}
