package com.xdx.sax.to;

import java.io.Serializable;

/**
 * QcCriteriaStepResultBO generated by hbm2java
 */
public class QcCriteriaStepResultTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private QcCriteriaStepTO qccriteriastep;
	private PlateSetTO plateset;
	private PlateSectionTO platesection;
	private Boolean pass;
	private Boolean isBorderline;
	private String resultvalue;

	public QcCriteriaStepResultTO() {
	}

	public QcCriteriaStepResultTO(long id, QcCriteriaStepTO qccriteriastep,
			PlateSetTO plateset, PlateSectionTO platesection) {
		this.id = id;
		this.qccriteriastep = qccriteriastep;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public QcCriteriaStepResultTO(long id, QcCriteriaStepTO qccriteriastep,
			PlateSetTO plateset, PlateSectionTO platesection, Boolean pass,
			String resultvalue) {
		this.id = id;
		this.qccriteriastep = qccriteriastep;
		this.plateset = plateset;
		this.platesection = platesection;
		this.pass = pass;
		this.resultvalue = resultvalue;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QcCriteriaStepTO getQccriteriastep() {
		return this.qccriteriastep;
	}

	public void setQccriteriastep(QcCriteriaStepTO qccriteriastep) {
		this.qccriteriastep = qccriteriastep;
	}

	public PlateSetTO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetTO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionTO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionTO platesection) {
		this.platesection = platesection;
	}

	public Boolean getPass() {
		return this.pass;
	}

	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	public Boolean getIsBorderline() {
		return isBorderline;
	}

	public void setIsBorderline(Boolean isBorderline) {
		this.isBorderline = isBorderline;
	}

	public String getResultvalue() {
		return this.resultvalue;
	}

	public void setResultvalue(String resultvalue) {
		this.resultvalue = resultvalue;
	}

}
