package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * QcCriteriaStepBO generated by hbm2java
 */
public class QcCriteriaStepTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private QcCriteriaStepTemplateTO qccriteriasteptemplate;
	private QcCriteriaTO qccriteria;
	private long ranking;
	private String passreturnresult;
	private String failreturnresult;
	private String assay1sub;
	private String assay2sub;
	private String yvalsub;
	private String zvalsub;
	private String processorStatus;
	private String normalizationClass;

	public QcCriteriaStepTO() {
	}

	public QcCriteriaStepTO(long id,
			QcCriteriaStepTemplateTO qccriteriasteptemplate,
			QcCriteriaTO qccriteria, long ranking) {
		this.id = id;
		this.qccriteriasteptemplate = qccriteriasteptemplate;
		this.qccriteria = qccriteria;
		this.ranking = ranking;
	}

	public QcCriteriaStepTO(long id,
			QcCriteriaStepTemplateTO qccriteriasteptemplate,
			QcCriteriaTO qccriteria, long ranking,
			String passreturnresult, String failreturnresult,
			String assay1sub, String assay2sub, String yvalsub, String zvalsub,
			String processorStatus, String normalizationClass) {
		this.id = id;
		this.qccriteriasteptemplate = qccriteriasteptemplate;
		this.qccriteria = qccriteria;
		this.ranking = ranking;
		this.passreturnresult = passreturnresult;
		this.failreturnresult = failreturnresult;
		this.assay1sub = assay1sub;
		this.assay2sub = assay2sub;
		this.yvalsub = yvalsub;
		this.zvalsub = zvalsub;
		this.processorStatus = processorStatus;
		this.normalizationClass = normalizationClass;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public QcCriteriaStepTemplateTO getQccriteriasteptemplate() {
		return this.qccriteriasteptemplate;
	}

	public void setQccriteriasteptemplate(
			QcCriteriaStepTemplateTO qccriteriasteptemplate) {
		this.qccriteriasteptemplate = qccriteriasteptemplate;
	}

	public QcCriteriaTO getQccriteria() {
		return this.qccriteria;
	}

	public void setQccriteria(QcCriteriaTO qccriteria) {
		this.qccriteria = qccriteria;
	}

	public long getRanking() {
		return this.ranking;
	}

	public void setRanking(long ranking) {
		this.ranking = ranking;
	}

	public String getPassreturnresult() {
		return this.passreturnresult;
	}

	public void setPassreturnresult(String passreturnresult) {
		this.passreturnresult = passreturnresult;
	}

	public String getFailreturnresult() {
		return this.failreturnresult;
	}

	public void setFailreturnresult(String failreturnresult) {
		this.failreturnresult = failreturnresult;
	}

	public String getAssay1sub() {
		return this.assay1sub;
	}

	public void setAssay1sub(String assay1sub) {
		this.assay1sub = assay1sub;
	}

	public String getAssay2sub() {
		return this.assay2sub;
	}

	public void setAssay2sub(String assay2sub) {
		this.assay2sub = assay2sub;
	}

	public String getYvalsub() {
		return this.yvalsub;
	}

	public void setYvalsub(String yvalsub) {
		this.yvalsub = yvalsub;
	}

	public String getZvalsub() {
		return this.zvalsub;
	}

	public void setZvalsub(String zvalsub) {
		this.zvalsub = zvalsub;
	}

	public String getProcessorStatus() {
		return this.processorStatus;
	}

	public void setProcessorStatus(String processorStatus) {
		this.processorStatus = processorStatus;
	}

	public String getNormalizationClass() {
		return this.normalizationClass;
	}

	public void setNormalizationClass(String normalizationClass) {
		this.normalizationClass = normalizationClass;
	}

}
