package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * QcCriteriaStepTemplateBO generated by hbm2java
 */
public class QcCriteriaStepTemplateTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private String templatestring;
	private String classname;

	public QcCriteriaStepTemplateTO() {
	}

	public QcCriteriaStepTemplateTO(long id, String name,
			String templatestring, String classname) {
		this.id = id;
		this.name = name;
		this.templatestring = templatestring;
		this.classname = classname;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTemplatestring() {
		return this.templatestring;
	}

	public void setTemplatestring(String templatestring) {
		this.templatestring = templatestring;
	}

	/**
	 * @return the classname
	 */
	public String getClassname() {
		return classname;
	}

	/**
	 * @param classname the classname to set
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}

}
