package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * QcResultFinalBO generated by hbm2java
 */
public class QcResultFinalTO implements java.io.Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private BigDecimal id;
	private PlateSetTO plateset;
	private PlateSectionTO platesection;
	private String saxqcresult;
	private String userqcresult;
	private String qcFailReason;
	private String createdby;
	private Date createddate;

	public QcResultFinalTO() {
	}

	public QcResultFinalTO(BigDecimal id, PlateSetTO plateset,
			PlateSectionTO platesection) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
	}

	public QcResultFinalTO(BigDecimal id, PlateSetTO plateset,
			PlateSectionTO platesection, String saxqcresult, String userqcresult,
			String qcFailReason, String createdby, Date createddate) {
		this.id = id;
		this.plateset = plateset;
		this.platesection = platesection;
		this.saxqcresult = saxqcresult;
		this.userqcresult = userqcresult;
		this.qcFailReason = qcFailReason;
		this.createdby = createdby;
		this.createddate = createddate;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public PlateSetTO getPlateset() {
		return this.plateset;
	}

	public void setPlateset(PlateSetTO plateset) {
		this.plateset = plateset;
	}

	public PlateSectionTO getPlatesection() {
		return this.platesection;
	}

	public void setPlatesection(PlateSectionTO platesection) {
		this.platesection = platesection;
	}

	public String getSaxqcresult() {
		return this.saxqcresult;
	}

	public void setSaxqcresult(String saxqcresult) {
		this.saxqcresult = saxqcresult;
	}

	public String getUserqcresult() {
		return this.userqcresult;
	}

	public void setUserqcresult(String userqcresult) {
		this.userqcresult = userqcresult;
	}

	/**
	 * @return the qcFailReason
	 */
	public String getQcFailReason() {
		return qcFailReason;
	}

	/**
	 * @param qcFailReason the qcFailReason to set
	 */
	public void setQcFailReason(String qcFailReason) {
		this.qcFailReason = qcFailReason;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

}
