package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * QcSchemaBO generated by hbm2java
 */
public class QcSchemaTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String schemaname;
	private Date createdate;
	private String creator;
	private Date modifydate;
	private String modifier;

	public QcSchemaTO() {
	}

	public QcSchemaTO(long id) {
		this.id = id;
	}

	public QcSchemaTO(long id, String schemaname, Date createdate,
			String creator, Date modifydate, String modifier) {
		this.id = id;
		this.schemaname = schemaname;
		this.createdate = createdate;
		this.creator = creator;
		this.modifydate = modifydate;
		this.modifier = modifier;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSchemaname() {
		return this.schemaname;
	}

	public void setSchemaname(String schemaname) {
		this.schemaname = schemaname;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

}
