package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

/**
 * RawWellDataBO generated by hbm2java
 */
public class RawWellDataTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private PlateTO plate;
	private AggregateTO aggregate;
	private WellTypeTO wellType;
	private long rownumber;
	private long columnnumber;
	private Integer loglinearleftend;
	private Integer loglinearrightend;
	private int errornum;
	private Double deltact;
	private Double bkgfam;
	private Double baselinefam;
	private Double saturationfam;
	private Double widthmetric;
	private Double ambiguitymetric;
	private Double xdxct;
	private Double cterror;
	private Double normalizedCt;
	private boolean isEmpty;

	public RawWellDataTO() {
	}

	public RawWellDataTO(long id, PlateTO plate, long rownumber,
			long columnnumber, WellTypeTO wellType) {
		this.id = id;
		this.plate = plate;
		this.wellType = wellType;
		this.rownumber = rownumber;
		this.columnnumber = columnnumber;
	}

	public RawWellDataTO(long id, PlateTO plate, AggregateTO aggregate,
			WellTypeTO wellType, long rownumber,
			long columnnumber,
			Integer loglinearleftend, Integer loglinearrightend,
			int errornum,
			Double deltact, Double bkgfam, Double baselinefam,
			Double saturationfam, Double widthmetric,
			Double ambiguitymetric, Double xdxct, Double cterror, Double normalizedCt, boolean isEmpty) {
		this.id = id;
		this.plate = plate;
		this.aggregate = aggregate;
		this.wellType = wellType;
		this.rownumber = rownumber;
		this.columnnumber = columnnumber;
		this.loglinearleftend = loglinearleftend;
		this.loglinearrightend = loglinearrightend;
		this.errornum = errornum;
		this.deltact = deltact;
		this.bkgfam = bkgfam;
		this.baselinefam = baselinefam;
		this.saturationfam = saturationfam;
		this.widthmetric = widthmetric;
		this.ambiguitymetric = ambiguitymetric;
		this.xdxct = xdxct;
		this.cterror = cterror;
		this.normalizedCt = normalizedCt;
		this.isEmpty = isEmpty;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PlateTO getPlate() {
		return this.plate;
	}

	public void setPlate(PlateTO plate) {
		this.plate = plate;
	}

	public AggregateTO getAggregate() {
		return this.aggregate;
	}

	public void setAggregate(AggregateTO aggregate) {
		this.aggregate = aggregate;
	}

	public WellTypeTO getWellType() {
		return this.wellType;
	}

	public void setWellType(WellTypeTO wellType) {
		this.wellType = wellType;
	}

	public long getRownumber() {
		return this.rownumber;
	}

	public void setRownumber(long rownumber) {
		this.rownumber = rownumber;
	}

	public long getColumnnumber() {
		return this.columnnumber;
	}

	public void setColumnnumber(long columnnumber) {
		this.columnnumber = columnnumber;
	}

	public Integer getLoglinearleftend() {
		return this.loglinearleftend;
	}

	public void setLoglinearleftend(Integer loglinearleftend) {
		this.loglinearleftend = loglinearleftend;
	}

	public Integer getLoglinearrightend() {
		return this.loglinearrightend;
	}

	public void setLoglinearrightend(Integer loglinearrightend) {
		this.loglinearrightend = loglinearrightend;
	}

	public int getErrornum() {
		return this.errornum;
	}

	public void setErrornum(int errornum) {
		this.errornum = errornum;
	}

	public Double getDeltact() {
		return this.deltact;
	}

	public void setDeltact(Double deltact) {
		this.deltact = deltact;
	}

	public Double getBkgfam() {
		return this.bkgfam;
	}

	public void setBkgfam(Double bkgfam) {
		this.bkgfam = bkgfam;
	}

	public Double getBaselinefam() {
		return this.baselinefam;
	}

	public void setBaselinefam(Double baselinefam) {
		this.baselinefam = baselinefam;
	}

	public Double getSaturationfam() {
		return this.saturationfam;
	}

	public void setSaturationfam(Double saturationfam) {
		this.saturationfam = saturationfam;
	}

	public Double getWidthmetric() {
		return this.widthmetric;
	}

	public void setWidthmetric(Double widthmetric) {
		this.widthmetric = widthmetric;
	}

	public Double getAmbiguitymetric() {
		return this.ambiguitymetric;
	}

	public void setAmbiguitymetric(Double ambiguitymetric) {
		this.ambiguitymetric = ambiguitymetric;
	}

	public Double getXdxct() {
		return this.xdxct;
	}

	public void setXdxct(Double xdxct) {
		this.xdxct = xdxct;
	}

	public Double getCterror() {
		return this.cterror;
	}

	public void setCterror(Double cterror) {
		this.cterror = cterror;
	}

	public Double getNormalizedCT() {
		return normalizedCt;
	}

	public void setNormalizedCT(Double d) {
		this.normalizedCt = d;
	}

	public boolean getIsEmpty() {
		return isEmpty;
	}

	public void setIsEmpty(boolean isEmpty) {
		this.isEmpty = isEmpty;
	}

}
