package com.xdx.sax.to;

// Generated Jan 21, 2009 4:04:43 PM by Hibernate Tools 3.2.4.CR1

import java.io.Serializable;

import com.xdx.sax.bo.ProcessBO;

/**
 * TestcodeBO generated by hbm2java
 */
public class TestcodeTO implements Serializable {

	//
	private static final long serialVersionUID = 1L;
	
	private long id;
	private String testcodename;
	private String testdescription;
	private QcSchemaTO qcSchema;

	public TestcodeTO() {
	}

	public TestcodeTO(long id, String testcodename, String testdescription) {
		this.id = id;
		this.testcodename = testcodename;
		this.testdescription = testdescription;
	}

	public TestcodeTO(long id, String testcodename, String testdescription,
			QcSchemaTO qcSchema) {
		this.id = id;
		this.testcodename = testcodename;
		this.testdescription = testdescription;
		this.qcSchema = qcSchema;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTestcodename() {
		return this.testcodename;
	}

	public void setTestcodename(String testcodename) {
		this.testcodename = testcodename;
	}

	public String getTestdescription() {
		return this.testdescription;
	}

	public void setTestdescription(String testdescription) {
		this.testdescription = testdescription;
	}

	public QcSchemaTO getQcSchema() {
		return this.qcSchema;
	}

	public void setQcSchema(QcSchemaTO qcSchema) {
		this.qcSchema = qcSchema;
	}

}
